apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "search.fullname" . }}-configmap
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "search.labels" . | nindent 4 }}
data:
  ELASTIC_URL: {{ .Values.config.elasticUrl | quote }}