apiVersion: v1
kind: ConfigMap
metadata:
  name: cart-configmap
  namespace: e-commerce
data:
  SPRING_REDIS_HOST: "redis-service.shared-services.svc.cluster.local"
  SPRING_REDIS_PORT: "6379"
  SPRING_REDIS_PASSWORD: ""
