apiVersion: v1
kind: ConfigMap
metadata:
  name: products-configmap
  namespace: e-commerce
data:
  MONGO_URI: "mongodb://mongo-root-username:mongo-root-password@mongo-service.shared-services.svc.cluster.local:27017/"
  DATABASE: "e-commerce"
