apiVersion: v1
kind: ConfigMap
metadata:
  name: store-configmap
  namespace: e-commerce
data:
  REACT_APP_PRODCUTS_URL_BASE: "http://products-service.e-commerce.svc.cluster.local:5000"
  REACT_APP_CART_URL_BASE: "http://cart-service.e-commerce.svc.cluster.local:8080"
