apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-ui-deployment
  namespace: e-commerce
spec:
  selector:
    matchLabels:
      app: store-ui-deployment
  template:
    metadata:
      labels:
        app: store-ui-deployment
    spec:
      containers:
      - name: store-ui
        image: prasad890/ecom-store-ui:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: REACT_APP_PRODCUTS_URL_BASE
          valueFrom:
            configMapKeyRef:
              name: store-configmap
              key: REACT_APP_PRODCUTS_URL_BASE
        - name: REACT_APP_CART_URL_BASE
          valueFrom:
            configMapKeyRef:
              name: store-configmap
              key: REACT_APP_CART_URL_BASE
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
