apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "store-ui.fullname" . }}-configmap
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "store-ui.labels" . | nindent 4 }}
data:
  REACT_APP_PRODCUTS_URL_BASE: {{ .Values.config.productsUrlBase | quote }}
  REACT_APP_CART_URL_BASE: {{ .Values.config.cartUrlBase | quote }}