apiVersion: v1
kind: Service
metadata:
  name: store-ui-service
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "store-ui.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: http
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
    {{- if and (eq "NodePort" .Values.service.type) .Values.service.nodePort }}
    nodePort: {{ .Values.service.nodePort }}
    {{- end }}
  selector:
    {{- include "store-ui.selectorLabels" . | nindent 4 }}