apiVersion: v1
kind: Service
metadata:
  name: products-service
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "products.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: http
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
  selector:
    {{- include "products.selectorLabels" . | nindent 4 }}