# Default values for Products service chart
# This is a YAML-formatted file.

nameOverride: ""
fullnameOverride: ""

namespace: e-commerce

image:
  repository: prasad890/ecom-products
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5000

config:
  mongoUri: mongodb://mongo-root-username:mongo-root-password@mongo-service.shared-services.svc.cluster.local:27017/
  database: e-commerce