apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: store-configmap
    literals: 
    - REACT_APP_PRODCUTS_URL_BASE=http://products-service.e-commerce.svc.cluster.local:5000
    - REACT_APP_CART_URL_BASE=http://cart-service.e-commerce.svc.cluster.local:8080
bases:
- ../../../base/store-ui
patchesStrategicMerge:
- service-nodeport.yaml
