apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mongodb.fullname" . }}-secret
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "mongodb.labels" . | nindent 4 }}
type: Opaque
data:
  mongo-root-username: {{ .Values.secrets.rootUsername | b64enc }}
  mongo-root-password: {{ .Values.secrets.rootPassword | b64enc }}